# Generated by Django 5.2.1 on 2025-07-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_clickevent_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickevent',
            name='ip',
        ),
    ]
