# Generated by Django 5.2.1 on 2025-07-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_remove_clickevent_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('powerbi_online', models.BooleanField(default=False)),
                ('powerbi_atualizado', models.BooleanField(default=False)),
                ('sistema_amei_online', models.BooleanField(default=True)),
            ],
        ),
    ]
