# Generated by Django 5.2.1 on 2025-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_sistemastatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemastatus',
            name='powerbi_odonto',
            field=models.BooleanField(default=False),
        ),
    ]
